### ISSUE TITLE
API Server is not working.....

### ISSUE THREAD

**Issue by iCloudsPWASaaS** [nirrek/wallfly#38]
API Server is not working.....please give the json/db file

http://54.66.236.15/api/users

**Comment by nirrek** [comment]
You can find the server source code here: https://github.com/nirrek/wallflyServer

Doesn't look like I added the schema or a DB setup script to that repo though 👎. So you'd need to create the DB structure yourself. You can infer the schema pretty easily from the handlers: https://github.com/nirrek/wallflyServer/blob/master/handlers/properties.js#L88
